void gpio_init();
void oled_init();
//string stateToString();
void displayState();
void displayInputSpeed(int y_pos);
void displayRPM(int y_pos);
void displayCurrent(int y_pos);
void displayPos(int y_pos);
void displayBat(int y_pos);
void displayForce(int y_pos);
void handleButton();
void handleRelease();
void handleMSCButton();
float getBatLevel();
long getInputSpeed();
float getRevolutions();
void getRPM();
void createDataFile();
void resetFiltering();
void activateMotor(bool direction, uint16_t power);
void testingSuite();
void testMSC();
void testSD();
void testSPI();